# config.yaml
TENANT_ID: "q3"
CLIENT_ID: "b0qa"
CLIENT_SECRET: "dq"
resource: "https://management.azure.com/"
ZENPAY_SUBID: "qb"
ZEN_WORKSPACE_ID: "3q1f"
AZLOG_ENDPOINT: "https://api.loganalytics.azure.com/v1/workspaces/"
AZDIAG_SCOPE: "https://api.loganalytics.io"
TOKEN_FILEPATH: "config/token.json"
TOKEN_FILEPATH_STR: "config/token.json"
AZDIAG_JSON_FILEPATH: "AZLOGS/AzDiag.json"
AZDIAG_JSON_FILEPATH_STR: "AZLOGS/AzDiag.json"
AZDIAG_CSV_FILEPATH: "AZLOGS/AzDiag.csv"
AZDIAG_CSV_FILEPATH_STR: "AZLOGS/AzDiag.csv"
AZDIAG_EXCEL_FILEPATH: "AZLOGS/AzDiag.xlsx"
AZDIAG_EXCEL_FILEPATH_STR: "AZLOGS/AzDiag.xlsx"
AZDIAG_EXCEL_FINAL_FILEPATH: "AZLOGS/AzDiag_FINAL.xlsx"
AZDIAG_RAWLOGS_FILEPATH: "AZLOGS/AzDiag_RAW.log"
AZDIAG_EXTRACTIONLOGS_FILEPATH_STR: "AZLOGS/AzDiag_sec.log"
AZDIAG_TMPCSV_FILEPATH: "AZLOGS/AzDiag_tmp.csv"
